apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: emsp-simulator

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - image-pull-secret.yaml
  - mysql-deployment.yaml
  - emsp-deployment.yaml

commonLabels:
  app.kubernetes.io/name: emsp-simulator
  app.kubernetes.io/environment: development

images:
  - name: ghcr.io/kenttannady/emsp-simulator
    newTag: latest
