apiVersion: v1
kind: Secret
metadata:
  name: emsp-simulator-secrets
  namespace: emsp-simulator
type: Opaque
data:
  # Base64 encoded values
  # echo -n 'emsp_password' | base64
  SPRING_DATASOURCE_PASSWORD: ZW1zcF9wYXNzd29yZA==
  # echo -n 'rootpassword' | base64  
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk
  # echo -n 'emsp_password' | base64
  MYSQL_PASSWORD: ZW1zcF9wYXNzd29yZA==
